name: student_brain
description: "StudentBrain — Intelligent Academic Command Center & Study Network Flutter Android App"
publish_to: 'none'
version: 2.6.5+57

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State Management
  flutter_riverpod: ^2.6.1

  # Navigation & Routing
  go_router: ^14.8.1

  # Network & API
  dio: ^5.8.0+1
  url_launcher: ^6.3.1

  # Local Storage & Security
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2

  # UI, Icons, Typography & Charts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  flutter_markdown: ^0.7.6+1
  uuid: ^4.5.1

  # Notifications
  flutter_local_notifications: ^18.0.1
  file_picker: ^8.1.7
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
